""" drop tables template and key_value

Revision ID: 50c185326733
Revises: 589925d004cd
Create Date: 2015-07-23 20:12:04.519980

"""

# revision identifiers, used by Alembic.
revision = '50c185326733'
down_revision = '589925d004cd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import logging

logger = logging.getLogger(__name__)

def upgrade():
    op.drop_table('template')
    op.drop_table('key_value')


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_value',
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name=u'key_value_pkey')
    )
    op.create_table('template',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('html', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'template_pkey')
    )
    ### end Alembic commands ###
